spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 418062724925-9ou23s69favr33e0tq2f6uruoa89tkit.apps.googleusercontent.com
            client-secret: FibKrmly5qfWJvK7_D0Zx_8S
            scope:
              - email
              - profile